#All the required parameters for the framework.
src_gpu_id = 0
tgt_gpu_id = 0
batch_size= None
dataset_name= None
src_dataset= None
tgt_dataset= None
model_root= None
learning_rate= None
learning_rate_ws= None
save_in_steps= None
log_in_steps= None
eval_in_steps= None
momentum= None
num_iter_warmstart= None
num_iter_adapt= None
warmstart_models= None
pseudo_threshold= None
manual_seed= None
warmstart_graph= None
lambda_tpl= None
Temperature= None
warmstart_i3d= None
num_segments= None
auto_resume= None
random_aux= None
lambda_bgm= None
max_gamma= None
base_dir = None
